apiVersion: batch/v1
kind: Job
metadata:
  name: mengine-bench-job
spec:
  template:
    spec:
      containers:
        - name: mengine-bench
          image: ghcr.io/triviajon/mengine-bench:nov-13
          imagePullPolicy: IfNotPresent
          command:
            [
              "bash",
              "-c",
              "eval $(opam env) && python3 benchmark.py run && python3 benchmark.py plot; echo 'Benchmark finished, pod sleeping...' && sleep infinity",
            ]
          workingDir: /root/foss/mengine-benchmarks
      restartPolicy: Never
  backoffLimit: 0
